# Generated by Django 5.0.4 on 2024-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
