# Generated by Django 5.0.4 on 2024-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
